### ISSUE TITLE
preferences page unthemed

### ISSUE THREAD

**Issue by zerofelero** [jadedkitty/LoudCloud-Enhanced-Extension#16]
![image](https://user-images.githubusercontent.com/55669377/65397804-e7b0bb80-dd67-11e9-8f84-b3f623aa8992.png)

**Comment by jadedzilla** [comment]
Resolved - styled preferences page, switched button to orange

**Comment by zerofelero** [comment]
button is strange combination of orange/blue-- might have broken?
![image](https://user-images.githubusercontent.com/55669377/66099921-a4233200-e55d-11e9-821c-5306bc727143.png)

**Comment by jadedzilla** [comment]
Should be matched with the assignment browse buttons, can probably add in the class for that one onto those selectors

**Comment by zerofelero** [comment]
derpy faded...

this issue is resolved...

opening new ticket for the creation of a secondary button theme'd semi-like this (#47)
