### ISSUE TITLE
correct colors for footer link pop-up boxes

### ISSUE THREAD

**Issue by zerofelero** [jadedkitty/LoudCloud-Enhanced-Extension#17]
![image](https://user-images.githubusercontent.com/55669377/65397852-48d88f00-dd68-11e9-958f-5d8b346c4f93.png)
![image](https://user-images.githubusercontent.com/55669377/65397863-5c83f580-dd68-11e9-93b9-5d09a2aad69c.png)

**Comment by jadedzilla** [comment]
Resolved

**Comment by zerofelero** [comment]
resolution seems to have been broken with white text

bottom of pop-up boxes and close buttons are not themed as well

**Comment by zerofelero** [comment]
corrected this issue via use of combination of CSS filters.

will be committing this change shortly.
