### ISSUE TITLE
Text and headers in profile page is unreadable and broken

### ISSUE THREAD

**Issue by jadedzilla** [jadedkitty/LoudCloud-Enhanced-Extension#22]
Text on the profile page is unreadable. Headers for personal information, guardians, address, etc. are broken and unreadable. User's display name is also unreadable.

**Comment by zerofelero** [comment]
corrected issue

the "Note: Your guardian information will always stay hidden from your peers" portion underneath guardian tab/section was purposely left harder to read-- not super important at this time.
