### ISSUE TITLE
files drop down unthemed

### ISSUE THREAD

**Issue by zerofelero** [jadedkitty/LoudCloud-Enhanced-Extension#43]
![image](https://user-images.githubusercontent.com/55669377/66099261-0c244900-e55b-11e9-9739-d53bd3501920.png)

**Comment by zerofelero** [comment]
have worked on this... however still needs some work (see 2nd picture below)
![image](https://user-images.githubusercontent.com/55669377/66542003-1c51a080-eae6-11e9-88f5-e232dd544eda.png)
![image](https://user-images.githubusercontent.com/55669377/66542033-37241500-eae6-11e9-9619-6711ca7f1cb6.png)
select all table cell is white when hovering over it.

**Comment by jadedzilla** [comment]
Fixed in 0f02a2031b40f1e138d775adbd00e36667766f35
